import { GoogleGenAI } from "@google/genai";
import { getStoredGeminiApiKey } from "../utils/geminiApiKey";

export async function generateImageEdit(base64Data: string, mimeType: string, prompt: string) {
  const apiKey = getStoredGeminiApiKey();
  if (!apiKey) {
    throw new Error("API Key is missing. Please enter your Gemini API key in the app.");
  }

  const ai = new GoogleGenAI({ apiKey });

  // Extract base64 part if it's a data URL
  const base64String = base64Data.includes(',') ? base64Data.split(',')[1] : base64Data;

  const response = await ai.models.generateContent({
    model: 'gemini-3.1-flash-image-preview',
    contents: {
      parts: [
        {
          inlineData: {
            data: base64String,
            mimeType: mimeType,
          },
        },
        { text: prompt },
      ],
    },
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
    }
  }
  
  throw new Error("No image generated by the model.");
}
